CREATE DATABASE IF NOT EXISTS WDA;

USE WDA;

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
NRDOC CHAR(30),
TELEFONE VARCHAR(80),
DT_NASCIMENTO DATE NULL,
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
SEXO VARCHAR(15),
RE INT(40),
CARGO VARCHAR(80),
SALARIO NUMERIC(13,2),
TG_PESSOA CHAR(1),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);

CREATE TABLE IF NOT EXISTS TS_LOGIN ( 

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
LOGIN VARCHAR(150),
SENHA VARCHAR(150),
PERMISSAO VARCHAR(60),
FK_FUNCIONARIO BIGINT NOT NULL,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
TG_INATIVO TINYINT DEFAULT 0,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_FUNCIONARIO) REFERENCES TB_FUNCIONARIO ( PK_ID )

);

CREATE TABLE IF NOT EXISTS TB_PRODUTO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
PRODUTO  VARCHAR(150),
VL_UNITARIO NUMERIC(13,2),
QUANTIDADE INTEGER,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);

CREATE TABLE IF NOT EXISTS TB_TIPOPAGAMENTO (
PK_ID BIGINT NOT NULL AUTO_INCREMENT,
TIPOPAGAMENTO VARCHAR(80),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);

CREATE TABLE IF NOT EXISTS TB_VENDA (
PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_CAIXA BIGINT NOT NULL,
FK_PRODUTO BIGINT NOT NULL,
FK_TIPOPAGAMENTO BIGINT NOT NULL,
QUANTIDADE INTEGER,
VL_LIQUIDO NUMERIC(13,2),
VL_TORAL NUMERIC(13,2),
TAXAJUROS NUMERIC(10),
NR_PARCELAS INTEGER,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_CAIXA) REFERENCES TS_LOGIN ( PK_ID ),
FOREIGN KEY (FK_PRODUTO) REFERENCES TB_PRODUTO ( PK_ID ),
FOREIGN KEY (FK_TIPOPAGAMENTO) REFERENCES TB_TIPOPAGAMENTO ( PK_ID )
);

INSERT INTO TB_FUNCIONARIO (NOME)VALUES('DARLAN');

INSERT INTO TS_LOGIN (LOGIN,SENHA,PERMISSAO,FK_FUNCIONARIO,DH_INCLUSAO)
VALUES('DARLAN','12345','CAIXA',1,NOW());

INSERT INTO TB_TIPOPAGAMENTO (TIPOPAGAMENTO, DH_INCLUSAO)
VALUES('DINHEIRO', NOW());

INSERT INTO TB_TIPOPAGAMENTO (TIPOPAGAMENTO, DH_INCLUSAO)
VALUES('CARTÃO DE CRÉDITO', NOW());

INSERT INTO TB_TIPOPAGAMENTO (TIPOPAGAMENTO, DH_INCLUSAO)
VALUES('CARTÃO DE DÉBITO', NOW());